name: "Install SUSE Observability Agent"
description: "Installs or upgrades SUSE Observability Agent via Helm using provided API key, cluster name and StackState URL."
author: "amolk"

inputs:
  stackstate_API_Key:
    description: "API key (treat as secret)."
    required: true
  stackstateClusterName:
    description: "Observed Cluster name"
    required: true
  stackstate_URL:
    description: "SUSE Observability cluster URL (receiver endpoint)."
    required: true
  Namespace:
    description: "Kubernetes namespace to install into."
    required: false
    default: "suse-observability"
  HelmRepo:
    description: "Helm repo URL or repo name (if chart repo must be added)."
    required: false
    default: "https://charts.rancher.com/server-charts/prime/suse-observability"
  ChartName:
    description: "Chart name (repo/chart or chart if repo added)."
    required: false
    default: "suse-observability/suse-observability-agent"
  ChartVersion:
    description: "Optional chart version constraint."
    required: false
    default: ""
  NodeagentskipTLSVerify:
    description: "Boolean: whether to set nodeAgent.skipKubeletTLSVerify (true/false)."
    required: false
    default: "true"
  GlobalskipSslValidation:
    description: "Boolean: whether to set global.skipSslValidation (true/false)."
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Repo checkout
      uses: actions/checkout@v4

    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Add Helm repo (if HelmRepo provided)
      shell: bash
      if: ${{ inputs.HelmRepo != '' }}
      run: |
        # attempt to add the repo (if value is a URL this will add; if it's an existing repo name this will harmlessly fail)
        helm repo add suse-observability "${{ inputs.HelmRepo }}" || true
        helm repo update
    
        helm upgrade --install suse-observability-agent suse-observability/suse-observability-agent \
          --namespace "${NAMESPACE}" --create-namespace \
          --set-string 'stackstate.apiKey'=${{inputs.stackstate_API_Key}} \
          --set-string 'stackstate.cluster.name'=${{inputs.stackstateClusterName}} \
          --set-string 'stackstate.url'=${{inputs.stackstate_URL}} \
          --set "nodeAgent.skipKubeletTLSVerify"=${{inputs.NodeagentskipTLSVerify}} \
          --set "global.skipSslValidation"=${{inputs.GlobalskipSslValidation}}
